#!/command/with-contenv sh
set -e

echo 'Inject into HTML page'
HTML_PAGES=$(find /www -name "*.html")
sed -i "s|###TITLE###|${TITLE}|" $HTML_PAGES
sed -i "s|###PLAYER_ROOT###|${PLAYER_ROOT}|" $HTML_PAGES

echo 'Starting web server'
python3 -m http.server 8080 --directory /www
